### ISSUE TITLE
opening project directory does not show projectionist commands

### ISSUE THREAD

**Issue by nhooyr** [c-brenn/phoenix.vim#4]
Like my project root is `~/code/phoenix/hello_world` and if I open it in Dirvish or netrw, `:Emodel` and friends are not defined. But if I open a file like `~/code/phoenix/hello_world/web/templates/page/index.html.eex` then `:Emodel` and friends are defined.

**Comment by nhooyr** [comment]
Seems to be an issue with projectionist. Sorry for the noise.

**Comment by nhooyr** [comment]
Just kidding, figured it out. making a PR

**Comment by nhooyr** [comment]
Ok so I added

```vim
augroup nhooyr_projectionist
  autocmd!
  autocmd FileType dirvish call ProjectionistDetect(resolve(expand('%:p')))
augroup END
```

to get projectionist to detect in Dirvish buffers. Now I need phoenix.vim to have the buffer setup before this call so that the buffer has `b:phoenix_root` set, otherwise setup_projections does nothing. I can either call phoenix.vim myself to setup the buffer or phoenix.vim can set it up for me in setup_projections. I'm opening a PR for option 2.

**Comment by c-brenn** [comment]
Nice fix. Unfortunately I haven't been giving this plugin much attention because I've been doing most of my elixir work in emacs (shame on me).

Perhaps another option would be to trigger a  `User Phoenix` event when a `User ProjectionistDetect` event happens.

Something like 
`autocmd User ProjectionistDetect if phoenix#detect() | call phoenix#setup_buffer() | endif`

I think if that was above [this line](https://github.com/c-brenn/phoenix.vim/blob/master/plugin/phoenix.vim#L27) everything would be set up nicely?

**Comment by nhooyr** [comment]
Sure, i'll modify my PR.

**Comment by c-brenn** [comment]
Or even better, you could change it to call [this function that I forgot was in there](https://github.com/c-brenn/phoenix.vim/blob/master/autoload/phoenix.vim#L27)

`autocmd User ProjectionistDetect call phoenix#setup()`

It will try and detect, and if it finds a phoenix project, will set up the buffer

**Comment by c-brenn** [comment]
Similar to rails.vim this plugin will only set up when you open an elixir buffer - this is a nice work around maybe

**Comment by nhooyr** [comment]
Ok, done!
