### ISSUE TITLE
Is this project up-to-date?

### ISSUE THREAD

**Issue by arcseldon** [c-brenn/phoenix.vim#9]
Looks like a great plugin - just a little concerned the git timestamps indicate it hasn't received much attention for at least 8 months. Do you keep it updated / know of any Phoenix changes that may have invalidated any of the templates or default locations for anything?   Am just getting up to speed with Phoenix hence the ask.  Again, thank you so much for providing this plugin.

**Comment by c-brenn** [comment]
I believe that Phoenix 1.3 made significant changes to how projects are laid out, which means this plugin probably has issues with Phoenix >= 1.3. I hadn't considered this because I haven't been doing any Phoenix work over the past months. Unfortunately I haven't been able to dedicate much time to maintaining this project over the past while due to other commitments.

In terms of fixing this plugin for phoenix 1.3; The changes should be pretty small so I may get a chance to get them done this weekend (but ofc if anyone else would like to take a look I would welcome a PR 😉 ). 

See this issue I just opened https://github.com/c-brenn/phoenix.vim/issues/10

Going to close this issue for now.

**Comment by arcseldon** [comment]
@c-brenn - thank you very much for reply. Understand your situation only too well.
